name: Deploy Microservice 1

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: microservice1
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image
      run: |
        IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
        docker build -t $IMAGE_URI ./microservice1
        docker push $IMAGE_URI
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Trigger Terraform Pipeline
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: kfir25/Terraform_AWS
        event-type: terraform-deploy
        client-payload: '{"microservice1_image": "${{ env.IMAGE_URI }}"}'



    # - name: Terraform Init & Apply
    #   run: |
    #     cd terraform
    #     terraform init -input=false
    #     terraform apply -auto-approve -input=false
    #   env:
    #     TF_VAR_image_tag: ${{ env.IMAGE_TAG }}
