name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      terraform-apply:
        type: boolean
        default: true
      microservice1_image:
        description: "Image URI for microservice 1"
        required: false
        default: "nginx"
      microservice2_image:
        description: "Image URI for microservice 2"
        required: false
        default: "nginx"
  # push:
  #   branches:
  #     - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        # with:
        #   terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init 
      
      - name: Terraform Workspace
        run: terraform workspace select "test" || terraform workspace new "test"

      - name: Terraform Plan
        env:
          TF_VAR_microservice_token: ${{ secrets.MICROSERVICE_TOKEN }}
        run: terraform plan -out=tfplan -input=false -var-file=TEST.tfvars

      - name: Terraform Apply
        env:
          TF_VAR_microservice_token: ${{ secrets.MICROSERVICE_TOKEN }}
        run: |
          if [[ "${{ github.event.inputs.terraform-apply }}" == 'true' ]]; then
          terraform apply -auto-approve -var="image_microservice1=${{ github.event.inputs.microservice1_image }}" -var="image_microservice2=${{ github.event.inputs.microservice2_image }}" tfplan
          fi
